### ISSUE TITLE
bytes per line 

### ISSUE THREAD

**Issue by dotnfc** [W-Mai/lvgl_image_converter#5]
你好，我在转换 800x400 的图片时，发现 .c 文件只输出了 1/2，
https://github.com/W-Mai/lvgl_image_converter/blob/fa4dd6b413c75468fa22186ab61f3759813d351e/lv_img_converter/lv_img_converter.py#L260

https://github.com/W-Mai/lvgl_image_converter/blob/fa4dd6b413c75468fa22186ab61f3759813d351e/lv_img_converter/lv_img_converter.py#L265

循环似乎没考虑 一个像素多个字节的情况。比如，565 格式是两个字节，那么 x_end 后面应该 * 2 才对。

**Comment by W-Mai** [comment]
谢谢你，你愿意提交一个pr修复一下这个问题吗？

**Comment by W-Mai** [comment]
已修复，感谢支持🙏
