### ISSUE TITLE
background transparent ?

### ISSUE THREAD

**Issue by cyberumut** [W-Mai/lvgl_image_converter#7]
hello dear, how to change background transparent  for true_color_alph with rgb565 

python3 lv_img_conv.py -f true_color_alpha -cf RGB565 -ff BIN -o test -r button.png
im using this command background color always white not transparent .
 
when i use lvgl online image convert same setting background transparent exported .

**Comment by W-Mai** [comment]
I debugged it and found that alpha can be output correctly when converting(without loading in lvgl, just see the output bin file). Can you provide your lvgl version and the pictures to be converted?
